# Generated by Django 5.2.8 on 2025-11-26 12:48

import archivebox.base_models.models
import charidfield.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pathlib
import statemachine.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0075_remove_snapshot_crawl_id_archiveresult_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('abid', charidfield.fields.CharIDField(blank=True, db_index=True, default=None, help_text='ABID-format identifier for this entity (e.g. snp_01BJQMF54D093DXEAWZ6JYRPAQ)', max_length=30, null=True, prefix='cws_', unique=True)),
                ('created_at', archivebox.base_models.models.AutoDateTimeField(db_index=True, default=None)),
                ('urls', models.TextField(blank=True, default='', help_text='The log of URLs discovered in this crawl, one per line, should be 1:1 with snapshot_set')),
                ('config', models.JSONField(default=dict)),
                ('max_depth', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('tags_str', models.CharField(blank=True, default='', max_length=1024)),
                ('persona_id', models.UUIDField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', help_text='A human-readable label for this crawl', max_length=64)),
                ('notes', models.TextField(blank=True, default='', help_text='Any extra notes this crawl should have')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('started', 'Started'), ('sealed', 'Sealed')], db_index=True, default='queued', max_length=15)),
                ('retry_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('output_dir', models.FilePathField(blank=True, default='', help_text='The directory to store the output of this crawl', path=pathlib.PurePosixPath('/home/daniel/workspace/ArchiveBox/archive'))),
                ('created_by', models.ForeignKey(default=archivebox.base_models.models.get_or_create_system_user_pk, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crawl',
                'verbose_name_plural': 'Crawls',
            },
            bases=(models.Model, statemachine.mixins.MachineMixin),
        ),
        migrations.CreateModel(
            name='CrawlSchedule',
            fields=[
                ('abid', charidfield.fields.CharIDField(blank=True, db_index=True, default=None, help_text='ABID-format identifier for this entity (e.g. snp_01BJQMF54D093DXEAWZ6JYRPAQ)', max_length=30, null=True, prefix='cws_', unique=True)),
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', archivebox.base_models.models.AutoDateTimeField(db_index=True, default=None)),
                ('schedule', models.CharField(help_text='The schedule to run this crawl on in CRON syntax e.g. 0 0 * * * (see https://crontab.guru/)', max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, default='', help_text='A human-readable label for this scheduled crawl', max_length=64)),
                ('notes', models.TextField(blank=True, default='', help_text='Any extra notes this crawl should have')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=archivebox.base_models.models.get_or_create_system_user_pk, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='The base crawl that each new scheduled job should copy as a template', on_delete=django.db.models.deletion.CASCADE, to='crawls.crawl')),
            ],
            options={
                'verbose_name': 'Scheduled Crawl',
                'verbose_name_plural': 'Scheduled Crawls',
            },
        ),
        migrations.AddField(
            model_name='crawl',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawls.crawlschedule'),
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('abid', charidfield.fields.CharIDField(blank=True, db_index=True, default=None, help_text='ABID-format identifier for this entity (e.g. snp_01BJQMF54D093DXEAWZ6JYRPAQ)', max_length=30, null=True, prefix='sed_', unique=True)),
                ('created_at', archivebox.base_models.models.AutoDateTimeField(db_index=True, default=None)),
                ('uri', models.URLField(db_index=True, help_text='The unique source location where URLs will be loaded from')),
                ('extractor', models.CharField(default='auto', help_text='The parser / extractor to use to load URLs from this source (default: auto)', max_length=32)),
                ('tags_str', models.CharField(blank=True, default='', help_text='An optional comma-separated list of tags to attach to any URLs that come from this source', max_length=255)),
                ('label', models.CharField(blank=True, default='', help_text='A human-readable label for this seed', max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(default=dict, help_text='An optional JSON object containing extra config to put in scope when loading URLs from this source')),
                ('notes', models.TextField(blank=True, default='', help_text='Any extra notes this seed should have')),
                ('output_dir', models.FilePathField(blank=True, default='', help_text='The directory to store the output of this crawl', path=pathlib.PurePosixPath('/home/daniel/workspace/ArchiveBox/archive'))),
                ('created_by', models.ForeignKey(default=archivebox.base_models.models.get_or_create_system_user_pk, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seed',
                'verbose_name_plural': 'Seeds',
                'unique_together': {('created_by', 'label'), ('created_by', 'uri', 'extractor')},
            },
        ),
        migrations.AddField(
            model_name='crawl',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crawl_set', to='crawls.seed'),
        ),
        migrations.CreateModel(
            name='Outlink',
            fields=[
                ('created_at', archivebox.base_models.models.AutoDateTimeField(db_index=True, default=None)),
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('src', models.URLField()),
                ('dst', models.URLField()),
                ('crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlink_set', to='crawls.crawl')),
                ('via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlink_set', to='core.archiveresult')),
            ],
            options={
                'unique_together': {('src', 'dst', 'via')},
            },
        ),
    ]
