# Generated by Django 5.2.8 on 2025-11-26 12:48

import archivebox.base_models.models
import archivebox.core.models
import django.db.models.deletion
import django.utils.timezone
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_snapshot_crawl_id_archiveresult_config_and_more'),
        ('crawls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='crawl',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_set', to='crawls.crawl'),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='cmd',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='end_ts',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='extractor',
            field=models.CharField(choices=[('htmltotext', 'htmltotext'), ('git', 'git'), ('singlefile', 'singlefile'), ('media', 'media'), ('archive_org', 'archive_org'), ('readability', 'readability'), ('mercury', 'mercury'), ('favicon', 'favicon'), ('pdf', 'pdf'), ('headers', 'headers'), ('screenshot', 'screenshot'), ('dom', 'dom'), ('title', 'title'), ('wget', 'wget')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='pwd',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snapshot'),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='start_ts',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('started', 'Started'), ('backoff', 'Waiting to retry'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=15),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Any extra notes this snapshot should have'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='output_dir',
            field=models.FilePathField(blank=True, default=None, match='.*', null=True, path=pathlib.PurePosixPath('/home/daniel/workspace/ArchiveBox/archive'), recursive=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='retry_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('queued', 'Queued'), ('started', 'Started'), ('backoff', 'Waiting to retry'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('sealed', 'Sealed')], db_index=True, default='queued', max_length=15),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='snapshot_set', through='core.SnapshotTag', through_fields=('snapshot', 'tag'), to='core.tag'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='timestamp',
            field=models.CharField(db_index=True, editable=False, max_length=32, unique=True, validators=[archivebox.core.models.validate_timestamp]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(default=archivebox.base_models.models.get_or_create_system_user_pk, on_delete=django.db.models.deletion.CASCADE, related_name='tag_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
