# Generated by Django 5.2.8 on 2025-11-26 17:27

import base_models.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KVTag',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', base_models.models.AutoDateTimeField(db_index=True, default=None)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('obj_id', models.UUIDField(db_index=True, default=None)),
                ('obj_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'core_kvtags',
                'abstract': False,
                'unique_together': {('obj_id', 'name')},
            },
        ),
    ]
